#!/bin/bash

echo -ne "\n"

is_update_available(){
  UPDATE_AVAILABLE=$(./helpr-modules.sh update-check -s)
  if [[ "$UPDATE_AVAILABLE" != "Helpr is up to date" ]]
  then
    echo -e $UPDATE_AVAILABLE"\nRun helpr update to install\n"
  fi
}

case "$1" in
  update)
    echo "Updating Helpr..."
    STATUS=$(curl -s -H 'Cache-Control: no-cache' -w "%{http_code}" https://raw.githubusercontent.com/rudradevpal/helpr/main/helpr-modules.sh --output helpr-modules.sh)
    if [[ "$STATUS" == "200" ]]
    then
      chmod +x helpr-modules.sh
      echo "Updated to "$(./helpr-modules.sh version)
    else
      echo "Update Failed!"
      echo -e "Error: helpr update - Unknown error. Please check your internet connection\n"
      exit 1
    fi
    ;;
  update-check)
    ./helpr-modules.sh "${@}";;
  *)
    is_update_available
    ./helpr-modules.sh "${@}";;
esac

echo -ne "\n"
